[phases.setup]
nixPkgs = ["nodejs", "python39", "chromium"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"
